/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
  public static void main(String args[]) {
    var problem = new org.example.Problem(1, 10, 69);
    problem.generate(5);
    var solution = problem.solve(50);
    System.out.println(problem);
    System.out.println(solution);
  }
}
